# Book settings
title: Demos for Eye Visualization
author: Benjamin J. Winjum
copyright: '2022'

# Launch button settings
repository:
  url: https://github.com/benjum/ocujum
  path_to_book: book
  branch: main

launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebe: true

sphinx:
  config:
    html_extra_path: ['assets']

execute:
  execute_notebooks: 'off'
